[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
memebet_arena = "Cm9MuUJsHtR5hgcp19KPX9HNu1wXmbTAg3t7a11zVGUb"

[programs.devnet]
memebet_arena = "CDjZHPYdWGK3p4cgWAT2nkrm45V2UmjSWoXTruadz3ty"

[programs.mainnet]
memebet_arena = "Cm9MuUJsHtR5hgcp19KPX9HNu1wXmbTAg3t7a11zVGUb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
